version: "3.0"

services:
  nginx:
    volumes:
      - ../nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/config/jaeger-config.json:/etc/jaeger-config.json
      - ../nginx/module/libjaegertracing_plugin.linux_amd64.so:/usr/local/lib/libjaegertracing_plugin.so
      - ../nginx/module/ngx_http_opentracing_module.so:/etc/nginx/modules/ngx_http_opentracing_module.so
    build:
      dockerfile: ../nginx/nginx.dockerfile
      context: ../nginx/
    container_name: nginx
    ports:
      - "8081:80"
    expose:
      - 4576
      - 9411
      - 16686
    networks:
      - minha-rede

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - minha-rede
    container_name: jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4576:4576"
      - "8080:8080"
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_OUTPUT=json
    volumes:
      - "../localstack/docker.sock:/var/run/docker.sock"
      - "../localstack/tmp:/tmp/localstack"
    networks:
      - minha-rede

#  mongo1:
#    image: mongo:4.2
#    container_name: mongo1
#    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
#    volumes:
#      - ./data/mongo-1:/data/db
#    ports:
#      - 30001:30001
#
#  mongo2:
#    image: mongo:4.2
#    container_name: mongo2
#    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
#    volumes:
#      - ./data/mongo-2:/data/db
#    ports:
#      - 30002:30002

networks:
  minha-rede:
    driver: bridge